# Orthogonal projection & inner product

#### The project map :
    1. Orthogonal projection onto high dimensional subspaces
    2. Orthogonal projection onto 1D subspace
This template allows you to create the vector and the matrix onto which you are projecting the vector

### Orthogonal projection onto N-dimension

In [11]:
import numpy as np
from numpy.linalg import inv as inv
from numpy.testing import assert_allclose as allclose
from numpy.testing import assert_array_almost_equal_nulp as equal

In [47]:
#Prompt user for vector and basis vector

# Vector v={v0, ..., vi}
v_len = int(input("What is the dimensionality of vector V? "))

print(f"Enter the vector by order to x0 to x{v_len-1}")

v = np.array([float(input(f"v{i}: ")) for i in range(v_len)])

check_v = input(f"Is this {v} your vector V? (y/n)").lower()


#Basis vectors matrix B={b0, ..., bi}
B_len = input("What is the dimensionality of the basis vectors matrix B? Write (N, D): ").split(",")

N, D = B_len

print("Input each of your matrix vectors:")

vectors = list()

for i in range(int(D)):
    B[i] = np.zeros(int(N))
    for n in range(int(N)):
        B[i][n] = float(input(f"b{n}: "))
    vectors.append(B[i])
    
B = np.column_stack(vectors)
    
check_B = input(f"""
Is this:

{B} 

your basis vector B? (y/n)""").lower()

check_B

What is the dimensionality of vector V? 3
Enter the vector by order to x0 to x2
v0: 6
v1: 0
v2: 0
Is this [6. 0. 0.] your vector V? (y/n)y
What is the dimensionality of the basis vectors matrix B? Write (N, D): 3, 2
Input each of your matrix vectors:
b0: 1
b1: 1
b2: 1
b0: 0
b1: 1
b2: 2

Is this:

[[1. 0.]
 [1. 1.]
 [1. 2.]] 

your basis vector B? (y/n)y


'y'

In [46]:
#For test

#1
x = np.array([12, 0, 0])
b1 = np.array([1, 1, 1])
b2 = np.array([0, 1, 2])
B = [b1, b2]
B_matrix = np.column_stack(B)

#2
x = np.array([6, 0, 0])
b1 = np.array([1, 1, 1])
b2 = np.array([0, 1, 2])
B = [b1, b2]
B_matrix = np.column_stack(B)

#3
x = np.array([3, 2, 2])
b1 = np.array([1, 0, 0])
b2 = np.array([0, 1, 1])
B = [b1, b2]
B_matrix = np.column_stack(B)

In [48]:
# Gram-Schmidt process 

def gram_schmidt(B):
    
    B_orthonormalized, _ = np.linalg.qr(B)
    return B_orthonormalized

#Projection

def p(v, B):
    #B @ inv(B.T @ B) @ B.T
    if np.sqrt(np.sum(B.T @ B)) == 0 :
        P = B @ inv(B.T @ B) @ B.T
        P_v = (P @ v).reshape((-1, 1))
    else : 
        B_norm = gram_schmidt(B)
        P = B_norm @ inv(B_norm.T @ B_norm) @ B_norm.T
        P_v = (P @ v).reshape((-1, 1))
    
    print(f"""
Projected vector is: 

{P_v}

Projection matrix is: 

{P}

Projection matrix rank is:

[{np.linalg.matrix_rank(P)}]
        """)
    
    
p(x, B_matrix)


Projected vector is: 

[[3.]
 [2.]
 [2.]]

Projection matrix is: 

[[1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]]

Projection matrix rank is:

[2]
        


### Orthogonal projection in a 1D subspace

In [27]:
#Prompt user for vector and basis vector

# Vector v={v0, ..., vi}
v_len = int(input("What is the dimensionality of vector V? "))

print(f"Enter the vector by order to x0 to x{v_len-1}")

v = np.array([float(input(f"v{i}: ")) for i in range(v_len)])

check_v = input(f"Is this {v} your vector V? (y/n)").lower()


#Basis vector B={b0, ..., bi}
B_len = int(input("What is the dimensionality of the basis vector B? "))

print(f"Enter the vector by order to b0 to b{B_len-1}")

B = np.array([float(input(f"b{i}: ")) for i in range(B_len)])

check_B = input(f"Is this {B} your basis vector B? (y/n)").lower()

check_B

if len(B) != len(v):
    print("The dimensions are not the same")

What is the dimensionality of vector V? 3
Enter the vector by order to x0 to x2
0: 1
1: 4
2: 2
Is this [1. 4. 2.] your vector V? (y/n)y
What is the dimensionality of the basis vector B? 4
Enter the vector by order to b0 to b3
0: 2
1: 1
2: 1
3: 3
Is this [2. 1. 1. 3.] your basis vector B? (y/n)y
The dimensions are not the same


In [14]:
B = np.array([1, 2, 2])
v = np.array([1, 1, 1])
np.outer(B, B)

array([[1, 2, 2],
       [2, 4, 4],
       [2, 4, 4]])

In [23]:
def p(v, B):
    N = len(B)
    P = np.outer(B, B)
    P /= np.sqrt(np.sum(B**2))**2
    P_v = (P @ v).reshape((-1, 1))
    print(f"""
Projected vector is:

{P_v}

Projection matrix is:

{P}

Projection matrix rank is:

[{np.linalg.matrix_rank(P)}]""")
#     else: # On process
#         B_norm = gram_schmidt(B)
#         P = P = (B[:, N] * B.T) / (np.linalg.norm(B)**2)
#         P_x = (P * x).reshape((-1, 1))
#         print(P_x)
        
p(v, B)


Projected vector is:

[[1.15384615]
 [0.76923077]]

Projection matrix is:

[[0.69230769 0.46153846]
 [0.46153846 0.30769231]]

Projection matrix rank is:

[1]
